project:
  type: website
  output-dir: docs

website:
  title: "Data Visualization 2025"
  description: "Part of the BDS Toolbox course in the Behavioral Data Science Master's at the University of Amsterdam"
  site-url: https://ann1ejohansson.github.io/data-visualization-2025/

  navbar:
    background: dark
    left:
      - href: index.qmd
        text: Home
      - href: https://github.com/ann1ejohansson/data-visualization-2025
        text: GitHub Repository
      - href: slides/slides.qmd
        text: Slides
      - href: assignments/assignment-1.qmd
        text: Assignment 1
      - href: assignments/assignment-2.qmd
        text: Assignment 2
      - text: Resources
        menu:
          - href: documents/working-on-the-server.qmd
            text: "Working on the server"
          - href: documents/git-workflow.qmd
            text: "Working with Git"
          - href: documents/ggplotly-handout.qmd
            text: "ggplotly"
          - href: https://socviz.co/
            text: "Data Visualization: A Practical Introduction (Healy)"
          - href: https://r4ds.hadley.nz/data-visualize.html
            text: "R for Data Science - Data visualization chapter"
          - href: https://canvas.uva.nl/courses/54361/modules
            text: "Videos on Canvas"


format:
  html:
    theme: cosmo         # Bootstrap theme (others: flatly, minty, etc.)
    toc: true            # Table of contents on each page
    toc-depth: 2
    number-sections: false
    code-copy: true      # Adds copy button to code blocks
